name: Flow of pipeline

on:
    push:
        branches: "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Logging to DockerHub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


            - name: Building and Pushing image to DockerHub
              run: |
                docker build -t sanan25/health-assessment-image:latest .
            - name: Checking image
              run: |
                docker images -a


    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps: 
            - name: Checking image
              run: |
                docker images -a
            - name: Deploying
              run: |
                docker push sanan25/health-assessment-image:latest

             
